services:
  ex1-mongodb:
    build:
      context: ./ex1
      dockerfile: Dockerfile.mongo
    container_name: ex1-mongodb
    volumes:
      - ex1mongoData:/data/db
    networks:
      - ex1net

  ex1-api:
    build: ./ex1
    container_name: ex1-data-api
    ports:
      - "17000:17000"
    depends_on:
      - ex1-mongodb
    environment:
      - MONGODB_URI=mongodb://ex1-mongodb/jogostabuleiro
      - PORT=17000
    networks:
      - ex1net

  ex2-mongodb:
    build:
      context: ./ex2
      dockerfile: Dockerfile.mongo
    container_name: ex2-mongodb
    volumes:
      - ex2mongoData:/data/db
    networks:
      - ex2net

  ex2-api:
    build: ./ex2
    container_name: ex2-api
    ports:
      - "19020:19020"
    depends_on:
      - ex2-mongodb
    environment:
      - MONGODB_URI=mongodb://ex2-mongodb/leituras
      - PORT=19020
    networks:
      - ex2net

  ex2-nginx:
    image: nginx:alpine
    container_name: ex2-nginx
    ports:
      - "19021:19021"
    volumes:
      - ./index.html:/usr/share/nginx/html/index.html:ro
      - ./ex2/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - ex2-api
    networks:
      - ex2net

volumes:
  ex1mongoData:
  ex2mongoData:

networks:
  ex1net:
    driver: bridge
  ex2net:
    driver: bridge