FROM mongo:latest
COPY filmes.json /docker-entrypoint-initdb.d/
COPY Atores.json /docker-entrypoint-initdb.d/
COPY Generos.json /docker-entrypoint-initdb.d/
COPY mongo-init/import.sh /docker-entrypoint-initdb.d/