services:
  mongodb:
    build:
      context: ./ex1
      dockerfile: Dockerfile.mongo
    container_name: mongodb_reparacoes
    networks:
      - reparacoes-network

  api:
    build:
      context: ./ex1
      dockerfile: Dockerfile
    container_name: api_reparacoes
    environment:
      - MONGO_URL=mongodb://mongodb:27017/autoRepair
    depends_on:
      - mongodb
    networks:
      - reparacoes-network
    ports:
      - "16025:16025" #PARA TESTE

  interface:
    build:
      context: ./ex2
      dockerfile: Dockerfile.interface
    container_name: interface_reparacoes
    ports:
      - "16026:16026"
    environment:
      - API_URL=http://api_reparacoes:16025
    depends_on:
      - api
    networks:
      - reparacoes-network

networks:
  reparacoes-network:
    driver: bridge
